import React, { useState } from 'react';
import { BidLog } from '../types.ts';
import { 
  Send, 
  Copy, 
  Check, 
  Clock, 
  DollarSign, 
  User, 
  Calendar, 
  Sparkles, 
  FileText 
} from 'lucide-react';

interface BidsHistoryProps {
  bids: BidLog[];
}

export const BidsHistory: React.FC<BidsHistoryProps> = ({ bids }) => {
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleCopy = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <Send className="h-5 w-5 text-emerald-400" />
            Bids Placed &amp; Proposals History
          </h2>
          <p className="text-xs text-slate-400">
            Automated proposal submissions generated by gpt-4o-mini (&lt;150 words)
          </p>
        </div>
        <div className="text-xs font-mono px-2.5 py-1 rounded-full bg-slate-800 text-slate-300 border border-slate-700">
          Total Logged: {bids.length}
        </div>
      </div>

      {bids.length === 0 ? (
        <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-12 text-center">
          <FileText className="h-10 w-10 text-slate-500 mx-auto mb-3" />
          <h3 className="text-base font-semibold text-slate-200">No bids submitted yet</h3>
          <p className="text-xs text-slate-400 mt-1 max-w-md mx-auto">
            Once projects pass your mandatory tech tags, budget, and blacklist filters, AI proposals will be automatically drafted and submitted here.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {bids.map((bid) => {
            const wordCount = bid.proposal.split(/\s+/).filter(Boolean).length;

            return (
              <div
                key={bid.id}
                className="bg-slate-900/80 border border-slate-800 hover:border-emerald-500/30 rounded-xl p-4 transition-all"
              >
                <div className="flex items-start justify-between gap-3 mb-2">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase ${
                        bid.status === 'SUCCESS'
                          ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                          : 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                      }`}>
                        {bid.status === 'SUCCESS' ? 'Live Bid Placed' : 'Dry-Run Simulated'}
                      </span>
                      <span className="text-xs text-slate-400 flex items-center gap-1">
                        <Clock className="h-3 w-3" />
                        {new Date(bid.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
                      </span>
                    </div>

                    <h3 className="text-base font-semibold text-slate-100">
                      {bid.projectTitle}
                    </h3>
                  </div>

                  <div className="text-right">
                    <div className="text-lg font-bold text-emerald-400 flex items-center justify-end">
                      <DollarSign className="h-4 w-4" />
                      {bid.bidAmount} {bid.currency}
                    </div>
                    <div className="text-xs text-slate-400">
                      in {bid.deliveryDays} days
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-4 text-xs text-slate-400 mb-3 pb-2 border-b border-slate-800">
                  <span className="flex items-center gap-1 text-slate-300">
                    <User className="h-3.5 w-3.5 text-slate-500" />
                    Client: <strong>{bid.clientUsername}</strong>
                  </span>
                  <span>•</span>
                  <span className="flex items-center gap-1 text-slate-300">
                    <Sparkles className="h-3.5 w-3.5 text-indigo-400" />
                    Length: <strong>{wordCount} words</strong> (Target: &lt;150w)
                  </span>
                </div>

                {/* Proposal Text */}
                <div className="relative group bg-slate-950/70 rounded-lg p-3.5 border border-slate-800/80 text-xs text-slate-200 leading-relaxed font-sans whitespace-pre-line">
                  <button
                    onClick={() => handleCopy(bid.id, bid.proposal)}
                    className="absolute top-2.5 right-2.5 flex items-center gap-1 text-[11px] px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition"
                  >
                    {copiedId === bid.id ? (
                      <>
                        <Check className="h-3 w-3 text-emerald-400" />
                        <span className="text-emerald-400">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="h-3 w-3" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                  {bid.proposal}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
